/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from "react";
import { useGLTF, Merged } from "@react-three/drei";

export default function MainScene3(props) {
  const { nodes } = useGLTF("./models/mainscene3-transformed.glb");
  const instances = useMemo(
    () => ({
      Cone: nodes.Cone_2,
      Cone1: nodes.Cone_3,
      Box: nodes.Box_2,
      Box1: nodes.Box_1,
      MergedObjects: nodes.Merged_Objects,
      MergedObjects1: nodes.Merged_Objects_1,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  );
}

function Model({ instances, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./models/mainscene3-transformed.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-0.009709, -0.057121, -0.00508]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      >
        <instances.Cone
          position={[-107.707544, -5.004806, 68.391655]}
          rotation={[0.699786, -1.101169, 1.249294]}
          scale={[0.508745, 0.508745, 0.457913]}
        />
        <instances.Cone
          position={[71.304724, -32.811249, 88.254832]}
          rotation={[0.945821, 0.535819, 0]}
          scale={0.457913}
        />
        <instances.Cone1
          position={[25.388656, -40.909777, 40.531219]}
          rotation={[2.08471, 0.578896, 2.340536]}
          scale={0.147991}
        />
        <instances.Cone1
          position={[-27.12224, -14.101236, 102.476567]}
          rotation={[-2.807925, -0.466904, Math.PI]}
          scale={0.257449}
        />
        <instances.Box
          position={[-2.167001, 18.7235, -5.713129]}
          rotation={[1.33134, -0.133428, -2.952281]}
        />
        <instances.Box1
          position={[-14.414208, 31.823111, 45.711128]}
          rotation={[1.33134, -0.133428, -2.952281]}
        />
        <instances.MergedObjects position={[60.520831, 4.491057, 20.674345]} />
        <instances.MergedObjects1
          position={[9.709244, -17.936859, 34.088013]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/mainscene3-transformed.glb");
