/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./models/mainscene4.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-0.01, -0.06, -0.01]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1}
      >
        <mesh
          geometry={nodes.Cone_2.geometry}
          material={materials["Clear Glass"]}
          position={[-107.71, -5, 68.39]}
          rotation={[0.7, -1.1, 1.25]}
          scale={[0.51, 0.51, 0.46]}
        />
        <mesh
          geometry={nodes.Cone.geometry}
          material={materials["Clear Glass"]}
          position={[71.3, -32.81, 88.25]}
          rotation={[0.95, 0.54, 0]}
          scale={0.46}
        />
        <mesh
          geometry={nodes.Cone_3.geometry}
          material={materials["Clear Glass"]}
          position={[25.39, -40.91, 40.53]}
          rotation={[2.08, 0.58, 2.34]}
          scale={0.15}
        />
        <mesh
          geometry={nodes.Cone_1.geometry}
          material={materials["Clear Glass"]}
          position={[-27.12, -14.1, 102.48]}
          rotation={[-2.81, -0.47, Math.PI]}
          scale={0.26}
        />
        <mesh
          geometry={nodes.Box_2.geometry}
          material={materials["Glass Decor"]}
          position={[-2.17, 18.72, -5.71]}
          rotation={[1.33, -0.13, -2.95]}
        />
        <mesh
          geometry={nodes.Box_1.geometry}
          material={materials["Glass Decor"]}
          position={[-14.41, 31.82, 45.71]}
          rotation={[1.33, -0.13, -2.95]}
        />
        <mesh
          geometry={nodes.Merged_Objects_1.geometry}
          material={materials.Wax}
          position={[60.52, 4.49, 20.67]}
        />
        <mesh
          geometry={nodes.Merged_Objects.geometry}
          material={materials.Blue}
          position={[9.71, -17.94, 34.09]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/mainscene4.glb");
