/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";

export default function SplineModel({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/GSy9Cu6gqXo7TNw2/scene.splinecode"
  );
  return (
    <>
      <color attach="background" args={["#4b4d52"]} />
      <group {...props} dispose={null}>
        <spotLight
          name="Spot Light 3"
          castShadow
          intensity={1}
          angle={Math.PI / 6}
          penumbra={0.5}
          distance={2000}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-fov={119.99999999999999}
          shadow-camera-near={100}
          shadow-camera-far={2500}
          position={[429.09, 0, -506.32]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 3]}
        />
        <spotLight
          name="Spot Light 2"
          castShadow
          intensity={1}
          angle={0.4}
          penumbra={0.5}
          distance={3026}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-fov={119.99999999999999}
          shadow-camera-near={100}
          shadow-camera-far={2500}
          position={[324.89, 145.3, 1026.21]}
          rotation={[-Math.PI, Math.PI / 3, -Math.PI / 2]}
        />
        <spotLight
          name="Spot Light"
          castShadow
          intensity={1}
          angle={0.3}
          penumbra={0.5}
          distance={2000}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-fov={119.99999999999999}
          shadow-camera-near={100}
          shadow-camera-far={2500}
          position={[-195.8, 1944.34, 0]}
        />
        <group name="Four" position={[-450.03, 100, -50]}>
          <mesh
            name="Cube 10"
            geometry={nodes["Cube 10"].geometry}
            material={materials["Cube 10 Material"]}
            castShadow
            receiveShadow
            position={[0, 50, -100]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            name="Cube 9"
            geometry={nodes["Cube 9"].geometry}
            material={materials["Cube 9 Material"]}
            castShadow
            receiveShadow
            position={[100, -50, 0]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            name="Cube 8"
            geometry={nodes["Cube 8"].geometry}
            material={materials["Cube 8 Material"]}
            castShadow
            receiveShadow
            position={[0, -50, 100]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            name="Cube 7"
            geometry={nodes["Cube 7"].geometry}
            material={materials["Cube 7 Material"]}
            castShadow
            receiveShadow
            position={[-100, 50, 0]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
        </group>
        <group name="Three" position={[1, 150, 401.57]}>
          <mesh
            name="Cube 6"
            geometry={nodes["Cube 6"].geometry}
            material={materials["Cube 6 Material"]}
            castShadow
            receiveShadow
            position={[-100, -100, -100]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            name="Cube 5"
            geometry={nodes["Cube 5"].geometry}
            material={materials["Cube 5 Material"]}
            castShadow
            receiveShadow
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            name="Cube 4"
            geometry={nodes["Cube 4"].geometry}
            material={materials["Cube 4 Material"]}
            castShadow
            receiveShadow
            position={[100, 100, 100]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
        </group>
        <group name="Two" position={[489.31, 50, -11.24]}>
          <mesh
            name="Cube 3"
            geometry={nodes["Cube 3"].geometry}
            material={materials["Cube 3 Material"]}
            castShadow
            receiveShadow
            position={[0, 0, 63.47]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            name="Cube 2"
            geometry={nodes["Cube 2"].geometry}
            material={materials["Cube 2 Material"]}
            castShadow
            receiveShadow
            position={[0, 0, -63.47]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
        </group>
        <group
          name="One"
          position={[1, 56.61, -409.61]}
          rotation={[0, -Math.PI / 4, 0]}
        >
          <spotLight
            name="Spot Light1"
            castShadow
            intensity={1}
            angle={Math.PI / 9}
            penumbra={0.5}
            distance={1800}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-fov={119.99999999999999}
            shadow-camera-near={100}
            shadow-camera-far={2500}
            position={[538.31, 1131.88, 392.03]}
          />
          <spotLight
            name="Spot Light2"
            castShadow
            intensity={1}
            angle={0.21}
            penumbra={0.5}
            distance={1287}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-fov={119.99999999999999}
            shadow-camera-near={100}
            shadow-camera-far={2500}
            position={[127.24, -64.48, -368.42]}
            rotation={[-Math.PI / 2, 0, 0.5]}
          />
          <spotLight
            name="Spot Light3"
            castShadow
            intensity={1}
            angle={0.21}
            penumbra={0.5}
            distance={1287}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-fov={119.99999999999999}
            shadow-camera-near={100}
            shadow-camera-far={2500}
            position={[1251.43, -121.09, 1125.76]}
            rotation={[-Math.PI / 2, 0, -2.41]}
          />
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials["Cube Material"]}
            castShadow
            receiveShadow
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
        </group>
      </group>
    </>
  );
}
